
Import('env_plugin')

env_plugin.Prepend(LIBS = [env_plugin['QWinMigratelib'], "user32"])
env_plugin.Append(CPPDEFINES = "QT_QTWINMIGRATE_IMPORT")
env_plugin.Append(CPPPATH = env_plugin["vstdir"] + r"\public.sdk\source\vst2.x")

env_plugin['vst_lib'] = env_plugin.StaticLibrary('vst', [env_plugin["vstdir"] + r"\public.sdk\source\vst2.x\audioeffect.cpp", env_plugin["vstdir"] + r"\public.sdk\source\vst2.x\audioeffectx.cpp", ])

env_plugin.SConscript([
   "variable_filter/SConstruct",
   "simple_EQ/SConstruct",
   "simple_overdrive/SConstruct",
       ])