
Import('env_plugin')

env_plugin.Prepend(LIBS = [env_plugin['QWinMigratelib'], "user32"])
env_plugin.Append(CPPDEFINES = "QT_QTWINMIGRATE_IMPORT")
env_plugin.Append(CPPPATH = env_plugin["vst"] + r"\public.sdk\source\vst2.x")

libmain = env_plugin.SharedLibrary('QtSimpleOverdrive', Glob("*.cpp") + [r"..\vstplug.def", env_plugin["vst"] + r"\public.sdk\source\vst2.x\audioeffect.cpp", env_plugin["vst"] + r"\public.sdk\source\vst2.x\audioeffectx.cpp", ])
libmain = env_plugin.Install('$LIBDIR', libmain)
